### ISSUE TITLE
The ability to add a page preview before publishing on the main page.

### ISSUE THREAD

**Issue by kalwas123** [jclusso/strapi-plugin-netlify-deployments#3]
It would be nice to be able to add a preview of the page before publishing it on the main page. Something similar to Gatsby Cloud Preview.

**Comment by jclusso** [comment]
PR's are welcome. At this point I'm not longer using Strapi myself.

**Comment by jclusso** [comment]
At this point I'm no longer using Strapi myself, but PRs are welcome.
