### ISSUE TITLE
config/plugins.js not existent by default

### ISSUE THREAD

**Issue by brfignoni** [jclusso/strapi-plugin-netlify-deployments#4]
Hello, 

Thank you for writting the netlify + strapi plugin tutorial.

_**Enable plugin configuration**
Open config/plugins.js file and add the netlify-deployments entry:_

As of strapi version 4.11.1, the "config" folder is inexistent, as well as the plugins.js file. You have to create the folder and the file manually. I think you should update the documentation, because it is confusing.

**Comment by jclusso** [comment]
@brfignoni where is this documented? Their [project structure](https://docs.strapi.io/dev-docs/project-structure) clearly shows this folder still exists.
