### ISSUE TITLE
Deploy On Render

### ISSUE THREAD

**Issue by anastasiiaxfr** [jclusso/strapi-plugin-netlify-deployments#5]
Hi, there! I have Strapi v4.11.4 and when added this plugin like npm i strapi-plugin-netlify-deployments and add to config/plugins.js `module.exports = ({ env }) => ({
  "netlify-deployments": {
    enabled: true,
  },
});`

There error to deploy on Render.com 
http://joxi.ru/p27GJOdsZJggl2 
http://joxi.ru/zANNwylHw7zzEA
Could you please tell me how fix this mistake. Thanks!

**Comment by jclusso** [comment]
This plugin is for Netlify, not render.
