### ISSUE TITLE
Add RBAC support?

### ISSUE THREAD

**Issue by laurenskling** [jclusso/strapi-plugin-netlify-deployments#7]
Wouldn't it be great if we could set some RBAC on this? For example, who is allowed to press the deploy button?

Personally, I would also like to hide the `title`, since I would like to give clients access to these logs and deploy button, but they don't need to read my silly commit messages ;)

**Comment by jclusso** [comment]
At this point I'm no longer using Strapi myself, but PRs are welcome.
